In [101]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [102]:
df = pd.read_csv("../dataset/diabetes.csv")
df = df.sample(frac = 1)
df.head()

,age,gender,polyuria,polydipsia,sudden_weight_loss,polyphagia,delayed_healing,obesity,class
123,47,Male,0,1,0,0,0,1,1
442,63,Male,1,1,1,1,0,1,1
46,60,Female,1,1,1,1,1,1,1
460,47,Male,0,0,0,0,0,0,0
282,45,Male,0,0,0,1,0,0,0

In [103]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [104]:
df["gender"] = df['gender'].replace(['Male', 'Female'], ["1", "0"])
df

,age,gender,polyuria,polydipsia,sudden_weight_loss,polyphagia,delayed_healing,obesity,class
123,47,1,0,1,0,0,0,1,1
442,63,1,1,1,1,1,0,1,1
46,60,0,1,1,1,1,1,1,1
460,47,1,0,0,0,0,0,0,0
282,45,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...
313,54,1,0,0,1,0,1,0,0
390,47,1,0,0,0,0,0,1,0
25,32,1,0,0,0,0,1,1,1
266,68,0,1,1,0,1,1,0,1
325,43,1,0,0,0,0,0,0,0

In [105]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [106]:
# Pisahkan fitur dan target untuk masing-masing set
train_feature = train.drop("class", axis=1)
train_target = train["class"]

validation_feature = validation.drop("class", axis=1)
validation_target = validation["class"]

test_feature = test.drop("class", axis=1)
test_target = test["class"]

In [107]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

In [108]:
# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

Validation classification_report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        19
           1       1.00      0.97      0.98        33

    accuracy                           0.98        52
   macro avg       0.97      0.98      0.98        52
weighted avg       0.98      0.98      0.98        52

Validation confusion_matrix:
[[19  0]
 [ 1 32]]
Validation accuracy_score:
0.9807692307692307

In [109]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.97      0.99        37

    accuracy                           0.98        52
   macro avg       0.97      0.99      0.98        52
weighted avg       0.98      0.98      0.98        52

Test confusion_matrix:
[[15  0]
 [ 1 36]]
Test accuracy_score:
0.9807692307692307

In [110]:
import pickle

pth = ""
# save the model to disk
filename = pth+'diabetes.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)

#print("accuracy_score :\n" + str(accuracy_score(test_target, y_pred2)))

0.9807692307692307